name: release
'on':
  push:
    branches:
      - main
      - tools-2.0.0

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  draft_release:
    permissions:
      contents: write # Allows this job to create releases

    strategy:
      fail-fast: true
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          # cache: 'npm'

      - run: yarn install --no-frozen-lockfile
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - name: Get Package Version
        id: get-version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - run: yarn build
      - run: yarn zip
      - run: yarn build:firefox
      - run: yarn zip:firefox

      - name: Set Release Flags
        id: release-flags
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/tools-2.0.0" ]]; then
            echo "::set-output name=prerelease::true"
          else
            echo "::set-output name=prerelease::false"
          fi

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ steps.get-version.outputs.version }}
          release_name: ${{ steps.get-version.outputs.version }}
          draft: true
          prerelease: ${{ steps.release-flags.outputs.prerelease }}
          files: |
            .output/autodarts-tools-${{ steps.get-version.outputs.version }}-chrome.zip
            .output/autodarts-tools-${{ steps.get-version.outputs.version }}-firefox.zip
